server:
  port: 9011

spring:
  application:
    name: order

  profiles:
    include: sharding_jdbc,mbp_dynamic

#mybatis plus 设置
mybatis-plus:
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.yangls.dynamicsource.entity
  mapper-locations: classpath:mapper/**.xml
  configuration:
    lazy-loading-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl